version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    volumes:
      - ./:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  db:
    image: sqlite3
    volumes:
      - ./database.db:/database.db